apiVersion: v1
kind: Secret
metadata:
  name: pg-admin-secret
type: Opaque
data:
  # Base64 encode the values 
  # superman@google.com= c3VwZXJtYW5AZ29vZ2xlLmNvbQ==
  # password: Nico&Sele
  # echo -n postgres | base64
  # cG9zdGdyZXM=
  PG_USER_EMAIL: c3VwZXJtYW5AZ29vZ2xlLmNvbQ==
  PG_USER_PASSWORD: TmljbyZTZWxl