apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  # Base64 encode the values 
  # postgres=cG9zdGdyZXM= 
  # password: Nico&Sele
  # echo -n postgres | base64
  # cG9zdGdyZXM=
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: TmljbyZTZWxl